#**Lista de Exercícios: Tensores em PyTorch**

Esta série de exercícios foi projetada para ajudar a consolidar o seu entendimento sobre o uso e manipulação de tensores, que são a base fundamental para o processamento de dados em PyTorch. Os tensores são estruturas de dados multidimensionais que formam a espinha dorsal de operações em aprendizado de máquina e processamento de dados.

Nesta lista, você irá explorar desde conceitos básicos, como a criação e manipulação de tensores, até operações mais avançadas, como broadcasting e reshaping. Ao final, você terá adquirido um sólido entendimento sobre como trabalhar com tensores no ecossistema PyTorch.

Instruções:
- Leia cada exercício atentamente e siga as instruções fornecidas.
- Complete cada exercício no espaço designado.
- Alguns exercícios podem exigir o uso de funções específicas do PyTorch.
- Certifique-se de consultar a documentação oficial quando necessário.

Lembre-se de que a prática é essencial para aprimorar suas habilidades em PyTorch. Vamos começar!

In [2]:
import torch


## **Exercício 1: Criando Tensores**
Crie um tensor 1D de números inteiros de 1 a 5.

In [3]:
# Resposta:
tensor_1d = torch.LongTensor([1, 2, 3, 4, 5])
print(tensor_1d)

tensor([1, 2, 3, 4, 5])


Crie um tensor 2D de números reais de 0 a 8 em uma matriz 2x4.

In [4]:
# Resposta:
tensor_2d = torch.FloatTensor([[0, 1, 2, 3], [4, 5, 6, 7]])
print(tensor_2d)

tensor([[0., 1., 2., 3.],
        [4., 5., 6., 7.]])


##**Exercício 2: Operações Básicas**

Multiplique o tensor 1D do exercicio anterior por 3

In [5]:
# Resposta:
tensor_1d = tensor_1d * 3
print(tensor_1d)

tensor([ 3,  6,  9, 12, 15])


Calcule o produto escala do tensor do exercício anterior com o tensor 1D criado na célula abaixo

In [6]:
tensor_1d_new = torch.LongTensor([-1, -10, 0, 2, 3])
print(tensor_1d_new)

tensor([ -1, -10,   0,   2,   3])


In [7]:
# Resposta:
produto_escalar = torch.dot(tensor_1d, tensor_1d_new)
print(produto_escalar)

tensor(6)


##**Exercício 3: Operações Avançadas**

Crie um tensor 1D de números inteiros de 1 a 16 e utilize o método view para transformar o tensor em uma matriz 4x4.

In [8]:
# Resposta:
tensor_1d = torch.LongTensor(range(1, 17))
tensor_2d = tensor_1d.view(4, 4)
print(tensor_2d)

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16]])


Divida o tensor 1D de 1 a 16 em 4 partes iguais.

In [9]:
# Resposta:
partes = torch.chunk(tensor_1d, 4)
print(partes)

(tensor([1, 2, 3, 4]), tensor([5, 6, 7, 8]), tensor([ 9, 10, 11, 12]), tensor([13, 14, 15, 16]))


Crie um novo tensor 2D empilhando essas partes verticalmente.

In [12]:
# Resposta:
tensor_2d = torch.stack(partes)
print(f'Vertical:\n{tensor_2d}\n')

# empilhando horizontalmente
tensor_2d = torch.stack(partes, dim=1)
print(f'Horizontal:\n{tensor_2d}')

Vertical:
tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16]])

Horizontal:
tensor([[ 1,  5,  9, 13],
        [ 2,  6, 10, 14],
        [ 3,  7, 11, 15],
        [ 4,  8, 12, 16]])
